const app=document.querySelector('#app'), audio=document.querySelector('#audio');
const fallback='logo.png'; let current=null, saveTimer=null;
const key='naheulbeuk-progress-v1';
const progress=()=>JSON.parse(localStorage.getItem(key)||'{}');
const saveProgress=(ep)=>{if(!ep||!Number.isFinite(audio.currentTime))return;const p=progress();p[ep.id]={time:audio.currentTime,duration:audio.duration||0,updated:Date.now()};localStorage.setItem(key,JSON.stringify(p));localStorage.setItem('naheulbeuk-last',ep.id)};
const fmt=s=>{if(!Number.isFinite(s))return '00:00';const m=Math.floor(s/60),r=Math.floor(s%60);return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`};
function home(){current=null;audio.pause();app.innerHTML=`<div class="shell"><header class="hero"><img class="logo" src="logo.png" alt="Le Donjon de Naheulbeuk"><p class="intro">Choisis un épisode et entre dans le donjon !</p></header><div class="content"><div class="search"><input id="q" type="search" placeholder="Rechercher un épisode…" aria-label="Rechercher"><div class="filters"><button class="chip active" data-season="all">Tous</button><button class="chip" data-season="1">S1</button><button class="chip" data-season="2">S2</button></div></div><div id="resume" class="resume"><button class="round">▶</button><div class="resume-info"><div class="eyebrow">Reprendre l'écoute</div><div class="resume-title"></div><div class="mini-bar"><span></span></div></div></div><h2 class="section-title">Tous les épisodes</h2><div id="grid" class="grid"></div><p class="install-note">Sur téléphone : ouvre le menu du navigateur puis « Ajouter à l'écran d'accueil ».</p></div></div>`;
 let season='all'; const q=document.querySelector('#q');
 const render=()=>{const term=q.value.trim().toLowerCase();const list=EPISODES.filter(e=>(season==='all'||String(e.season)===season)&&(`${e.episode} ${e.title}`.toLowerCase().includes(term)));document.querySelector('#grid').innerHTML=list.length?list.map(e=>`<article class="card" data-id="${e.id}"><img class="thumb" src="${e.image||fallback}" alt=""><div class="card-body"><h3>${escapeHtml(e.title)}</h3><p class="meta">Saison ${e.season} · Épisode ${e.episode}</p></div></article>`).join(''):`<div class="empty">Aucun épisode trouvé.</div>`;document.querySelectorAll('.card').forEach(c=>c.onclick=()=>player(c.dataset.id));};
 q.oninput=render;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');season=b.dataset.season;render()});render();
 const last=localStorage.getItem('naheulbeuk-last'),ep=EPISODES.find(x=>x.id===last),p=ep&&progress()[ep.id];if(ep&&p&&p.time>5){const r=document.querySelector('#resume');r.classList.add('show');r.querySelector('.resume-title').textContent=`Épisode ${ep.episode} — ${ep.title}`;r.querySelector('span').style.width=`${p.duration?Math.min(100,p.time/p.duration*100):10}%`;r.onclick=()=>player(ep.id)}
}
function player(id){const ep=EPISODES.find(e=>e.id===id);if(!ep)return home();current=ep;const idx=EPISODES.indexOf(ep),prev=EPISODES[idx-1],next=EPISODES[idx+1];app.innerHTML=`<div class="shell player"><div class="player-top"><button class="back" aria-label="Retour">←</button><div class="badge">S${ep.season} · E${ep.episode}</div><span style="width:54px"></span></div><img class="cover" src="${ep.image||fallback}" alt="Illustration de l'épisode"><h1>${escapeHtml(ep.title)}</h1><p class="subtitle">Le Donjon de Naheulbeuk</p><div class="progress-wrap"><input class="progress" type="range" min="0" max="100" value="0"><div class="times"><span class="elapsed">00:00</span><span class="duration">00:00</span></div></div><div class="controls"><button class="ctrl rewind">↶<small>10</small></button><button class="ctrl play">▶</button><button class="ctrl forward">↷<small>30</small></button></div><div class="navrow"><button class="navbtn prev" ${prev?'':'disabled'}>← Épisode précédent</button><button class="navbtn next" ${next?'':'disabled'}>Épisode suivant →</button></div></div>`;
 document.querySelector('.back').onclick=home;document.querySelector('.prev').onclick=()=>prev&&player(prev.id);document.querySelector('.next').onclick=()=>next&&player(next.id);
 audio.src=ep.audio;const stored=progress()[ep.id];audio.onloadedmetadata=()=>{if(stored?.time&&stored.time<audio.duration-5)audio.currentTime=stored.time;update()};audio.ontimeupdate=update;audio.onplay=()=>document.querySelector('.play').textContent='Ⅱ';audio.onpause=()=>document.querySelector('.play').textContent='▶';audio.onended=()=>{saveProgress(ep);if(next)player(next.id)};
 document.querySelector('.play').onclick=()=>audio.paused?audio.play():audio.pause();document.querySelector('.rewind').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-10);document.querySelector('.forward').onclick=()=>audio.currentTime=Math.min(audio.duration||Infinity,audio.currentTime+30);document.querySelector('.progress').oninput=e=>{if(audio.duration)audio.currentTime=audio.duration*e.target.value/100};clearInterval(saveTimer);saveTimer=setInterval(()=>saveProgress(current),5000);
}
function update(){if(!current)return;const bar=document.querySelector('.progress');if(!bar)return;bar.value=audio.duration?audio.currentTime/audio.duration*100:0;document.querySelector('.elapsed').textContent=fmt(audio.currentTime);document.querySelector('.duration').textContent=fmt(audio.duration)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.addEventListener('beforeunload',()=>saveProgress(current));window.addEventListener('hashchange',home);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');home();
